name: Ipk
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: setup dotnet8
        uses: actions/setup-dotnet@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          dotnet-version: 8.0.x
      
      - name: setup ipk
        run: sudo apt-get install binutils tar gzip

      - name: chmod shell
        run: sed -i 's/\r$//' publish-ipk.sh
      - name: chmod shell
        run: chmod +x publish-ipk.sh
      - name: publish projects
        run: ./publish-ipk.sh
    
      - name: get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    