name: Publich

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: setup dotnet7
      uses: actions/setup-dotnet@v2
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        dotnet-version: 7.0.x

    - name: setup dotnet8
      uses: actions/setup-dotnet@v2
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        dotnet-version: 8.0.x
    - name: setup msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
  
    - name: publish projects
      run: ./publish.bat

    - name: get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    
    - name: create release
      id: create_release
      uses: GongT/actions-recreate-release@v1
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        tag_name: v1.2.0.2
        release_name: v1.2.0.2.${{ steps.date.outputs.today }}
        draft: false
        prerelease: false
        body: |
          1. 网关层级计算修复(在linux下计算错误导致打洞失败)
          2. 修复在IPV6环境下域名解析缓慢问题
          3. 新增基于端口映射的打洞协议
          4. 修复端口转发潜在BUG
          5. 虚拟网卡支持广播组播了
          6. 修复了socks5的一些问题
          7. 增加了docker宿主机访问策略，docker也可以用虚拟网卡通信了
          8. 请更新服务端

    - name: upload win x64
      id: upload-win-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-win-x64.zip
        asset_name: linker-win-x64.zip
        asset_content_type: application/zip

    - name: upload win arm64
      id: upload-win-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-win-arm64.zip
        asset_name: linker-win-arm64.zip
        asset_content_type: application/zip

    - name: upload linux x64
      id: upload-linux-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-linux-x64.zip
        asset_name: linker-linux-x64.zip
        asset_content_type: application/zip

    - name: upload linux arm64
      id: upload-linux-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-linux-arm64.zip
        asset_name: linker-linux-arm64.zip
        asset_content_type: application/zip

    - name: upload linux musl x64
      id: upload-linux-musl-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-linux-musl-x64.zip
        asset_name: linker-linux-musl-x64.zip
        asset_content_type: application/zip

    - name: upload linux musl arm64
      id: upload-linux-musl-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-linux-musl-arm64.zip
        asset_name: linker-linux-musl-arm64.zip
        asset_content_type: application/zip

    - name: upload osx x64
      id: upload-osx-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-osx-x64.zip
        asset_name: linker-osx-x64.zip
        asset_content_type: application/zip

    - name: upload osx arm64
      id: upload-osx-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/linker-osx-arm64.zip
        asset_name: linker-osx-arm64.zip
        asset_content_type: application/zip