name: Publich

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: setup dotnet7
      uses: actions/setup-dotnet@v2
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        dotnet-version: 7.0.x

    - name: setup dotnet8
      uses: actions/setup-dotnet@v2
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        dotnet-version: 8.0.x
    - name: setup msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    - name: publish extends
      run: ./publish-extends.bat

    - name: publish projects
      run: ./publish.bat

    - name: get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    
    - name: create release
      id: create_release
      uses: GongT/actions-recreate-release@v1
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        tag_name: v1.0.0.0
        release_name: v1.0.0.0.${{ steps.date.outputs.today }}
        draft: false
        prerelease: false
        
    - name: upload win x64
      id: upload-win-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/cmonitor-win-x64.zip
        asset_name: cmonitor-win-x64.zip
        asset_content_type: application/zip

    - name: upload win arm64
      id: upload-win-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/cmonitor-win-arm64.zip
        asset_name: cmonitor-win-arm64.zip
        asset_content_type: application/zip

    - name: upload linux x64
      id: upload-linux-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/cmonitor-linux-x64.zip
        asset_name: cmonitor-linux-x64.zip
        asset_content_type: application/zip

    - name: upload linux arm64
      id: upload-linux-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/cmonitor-linux-arm64.zip
        asset_name: cmonitor-linux-arm64.zip
        asset_content_type: application/zip

    - name: upload osx x64
      id: upload-osx-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/cmonitor-osx-x64.zip
        asset_name: cmonitor-osx-x64.zip
        asset_content_type: application/zip

    - name: upload osx arm64
      id: upload-osx-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/cmonitor-osx-arm64.zip
        asset_name: cmonitor-osx-arm64.zip
        asset_content_type: application/zip

